name: daily
description: "Multi-meeting standup organizer with notes and timers."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.4
  uuid: ^4.5.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
